# Generated by Django 4.0.1 on 2022-12-06 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('birthdate', models.DateField()),
                ('icon', models.CharField(default='pawprint', max_length=30)),
                ('color', models.CharField(default='AFC-blue', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
        migrations.CreateModel(
            name='ReminderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('completion', models.BooleanField(default=False)),
                ('icon', models.CharField(default='exclamationmark.circle', max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=250)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.petmodel')),
            ],
        ),
    ]
