# Generated by Django 4.0.1 on 2022-12-06 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_petmodel_rename_login_user_username_remindermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmodel',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='remindermodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 6, 22, 4, 14, 422702)),
        ),
    ]
