# Generated by Django 4.0.1 on 2022-12-06 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_petmodel_birthdate_alter_remindermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='birthdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
