# Generated by Django 4.0.1 on 2022-12-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_petmodel_birthdate_alter_petmodel_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetModel',
            new_name='Pet',
        ),
        migrations.RenameModel(
            old_name='ReminderModel',
            new_name='Reminder',
        ),
    ]
